name: Examples

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        example:
          - "examples/arduino-blink"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      # On Linux, wxPython ("needed" for flash_writer.py)
      # has a dependency on GTK+. Install it here.
      # the tool just uses it to show a EULA dialog,
      # so not critical, let's drop it later.. 
      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install -y libgtk-3-dev
            pip install -U wheel
            pip install -U wxPython
          fi
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --global --platform symlink://.
        shell: bash
      - name: Build examples
        run: |
          pio run -d ${{ matrix.example }}
